//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string AdditionalInfos { get; set; }
        public long CustomerNr { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
