//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public Machine()
        {
            this.MachineOrder = new HashSet<MachineOrder>();
        }
    
        public long ID { get; set; }
        public int FabricationNumber { get; set; }
        public string SD { get; set; }
        public string Version { get; set; }
        public string Type { get; set; }
        public string Reference { get; set; }
        public Nullable<long> Plant { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<long> KVZ { get; set; }
    
        public virtual ICollection<MachineOrder> MachineOrder { get; set; }
    }
}
