//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineOrder
    {
        public MachineOrder()
        {
            this.MachineProperties = new HashSet<MachineProperty>();
            this.Tasks = new HashSet<Task>();
        }
    
        public long ID { get; set; }
        public bool Checked { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual ICollection<MachineProperty> MachineProperties { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
