//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OracleData : DbContext
    {
        public OracleData()
            : base("name=OracleData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Opt> Opts { get; set; }
        public DbSet<Machine> Machines { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<MachineProperty> MachineProperties { get; set; }
        public DbSet<Property> Properties { get; set; }
        public DbSet<Rule> Rules { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<Operation> Operations { get; set; }
        public DbSet<Time> Times { get; set; }
        public DbSet<MachineOrder> MachineOrder { get; set; }
    }
}
