//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Operation
    {
        public long ID { get; set; }
        public string Operator { get; set; }
        public short X { get; set; }
        public short Y { get; set; }
        internal string Type { private get; set; }
    
        public virtual Rule Rule { get; set; }
    }
}
