//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Opts = new HashSet<Opt>();
            this.Time = new HashSet<Time>();
            this.MachineOrders = new HashSet<MachineOrder>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Note { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public long Number { get; set; }
        public bool Done { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Opt> Opts { get; set; }
        public virtual ICollection<Time> Time { get; set; }
        public virtual ICollection<MachineOrder> MachineOrders { get; set; }
    }
}
