//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.OrderProperties = new HashSet<MachineProperty>();
            this.Condition = new HashSet<Condition>();
        }
    
        public long ID { get; set; }
        public string Text { get; set; }
    
        public virtual ICollection<MachineProperty> OrderProperties { get; set; }
        public virtual ICollection<Condition> Condition { get; set; }
    }
}
