//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public Rule()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public int Priority { get; set; }
        public short X { get; set; }
        public short Y { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual User Owner { get; set; }
    }
}
