//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Rules = new HashSet<Rule>();
            this.MachineOrders = new HashSet<MachineOrder>();
        }
    
        public long ID { get; set; }
        public string Text { get; set; }
    
        public virtual ICollection<Rule> Rules { get; set; }
        public virtual ICollection<MachineOrder> MachineOrders { get; set; }
    }
}
