//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Time = new HashSet<Time>();
            this.Rules = new HashSet<Rule>();
        }
    
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Time> Time { get; set; }
        public virtual ICollection<Rule> Rules { get; set; }
    }
}
